# Generated by Django 4.2.3 on 2023-07-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=255)),
                ('Idade', models.IntegerField()),
            ],
        ),
    ]
