# Generated by Django 4.2.3 on 2023-07-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
