# Generated by Django 4.2.3 on 2023-07-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ID_Usuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Idade',
            new_name='idade',
        ),
    ]
