# Generated by Django 4.2.3 on 2023-07-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0003_rename_id_usuario_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Nome',
            new_name='nome',
        ),
    ]
